---
- name: IOS Add User Demo
  hosts: routers_ssh_pass
  tasks:
    - name: Add User
      ios_user:
        name: ansible_admin
        hashed_password:
          type: 5
          value: $1$pass$q.8O0ezj5JxZNEcvsQvQR0
        privilege: 15
        state: present
      register: add_user
    - debug:
        var: add_user.commands