---
- hosts: SW-01
  gather_facts: true
  connection: local

  tasks:
  - name: show run
    ios_command:
      commands:
        - show run
      host: "{{ ansible_host }}"
      username: cisco
      passdword: Sistemas11
      register: config
  - name: save
    copy:
    content: "{{ config.stdout[0]}}"
    dest: "home/ansibledemo/backups/show_run{{ inventory_hostname }}.txt"
