---
- name: Configurar VLAN
  hosts: switchs

  tasks:
  - name: Crear VLAN
    ios_vlans:
      config:
        - name: vlan_100
          vlan_id: 100
          shutdown: enabled
          state: suspend
      state: merged
    register: vln

  - debug:
    var: vln.before
  - debug:
    var: vln.commands
  - debug:
    var: vln.after