---
- name: DEMOSTRACIÓN ELECTRODATA
  hosts: vm-ubuntu
  become: yes
  vars_files:
      - default.yml

  tasks:
  - name: Install latest version of Apache
    apt: name=apache2 update_cache=yes state=latest

  - name: Create document root for domain configured in host variable
    file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
  
  - name: Copy your index file
    template:
      src: "index-template.html"
      dest: "/var/www/{{ http_host }}/index.html"

  - name: Set up virtuahHost
    template:
      src: "apache-template.conf"
      dest: "/etc/apache2/sites-available/{{ http_conf }}"

  - name: Enable site
    shell: a2ensite {{ http_conf }}
    notify: Reload Apache
    
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted